eggdrop 1.3.0

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,5 +1,5 @@
 dnl Process this file with autoconf to produce a configure script.
-AC_INIT(eggdrop.conf)
+AC_INIT(eggdrop.conf.dist)
 AC_CONFIG_HEADER(config.h)
 
 echo ""
@@ -15,8 +15,6 @@ AC_AIX
 AC_ISC_POSIX
 AC_MINIX
 dnl no cross-compiling!
-AC_C_CROSS  
-dnl <- was merged into AC_PROG_CC - not on my auto-conf :/
 
 if test ! x${cross_compiling} = xno; then
   echo ""
@@ -65,18 +63,11 @@ DLOPEN_1=1
 case $system in
   Linux)
     CFLAGS="${CFLAGS} -Wall"
-    AC_MSG_RESULT(Linux! lets get down an boogey)
-    SHLIB_LD="${CC} -shared"
-    BEL_MOD_LD="${CC} -rdynamic"
+    AC_MSG_RESULT(Linux! It's what all good llama's use)
+    SHLIB_LD="${CC} -shared -nostartfiles"
+    BEL_MOD_LD="${CC}"
     AC_DEFINE(MODULES_OK)
     LINUX=yes
-    DLOPEN_1=
-    ;;
-  FreeBSD)
-    AC_MSG_RESULT(FreeBSD r0x th3 h0u53 -- You're l33t! enjoy!)
-    SHLIB_CC="$CC -fpic"
-    SHLIB_LD="ld -Bshareable -x"
-    AC_DEFINE(MODULES_OK)
     DLOPEN_1=
     ;;
   BSD/OS)
@@ -89,9 +80,23 @@ case $system in
       SHLIB_STRIP="touch"
       AC_DEFINE(MODULES_OK)
     else
-      AC_MSG_RESULT(BSD/OS 2! statically linked modules are you only choice)
+      AC_MSG_RESULT(BSD/OS 2! statically linked modules are the only choice)
       DEFAULT_MAKE=static
     fi
+    AC_CHECK_PROG(GMAKE,gmake,gmake)
+    if test "x$GMAKE" = "x"; then
+      echo ""
+      echo "Yoicks! you have BSD/OS & you dont have 'gmake', you may"
+      echo "not be able to compile the bot successfully :("
+      echo ""
+    fi
+    ;;
+  *BSD)
+    AC_MSG_RESULT(FreeBSD/NetBSD - choose your poison)
+    SHLIB_CC="$CC -fpic"
+    SHLIB_LD="ld -Bshareable -x"
+    AC_DEFINE(MODULES_OK)
+    DLOPEN_1=
     ;;
   SunOS)
     if test x`uname -r | cut -d . -f 1` = "x5"; then
@@ -111,7 +116,7 @@ case $system in
     case `uname -r | cut -d . -f 1` in
       V*)
         AC_MSG_RESULT(Digital OSF)
-	SHLIB_LD='ld -shared -expect_unresolved "*"'
+	SHLIB_LD="ld -shared -expect_unresolved '*'"
 	SHLIB_STRIP="touch"
         AC_DEFINE(MODULES_OK)
         ;;
@@ -171,7 +176,7 @@ else
   if test x`${UNAME}` = "xSunOS"; then
     AC_MSG_CHECKING(for SunOS 4)
     if test x`uname -r | cut -d . -f 1` = "x5"; then
-      AC_MSG_RESULT(Solaris -- yay)
+      AC_MSG_RESULT(Solaris -- "*bollocks*" zarni )
     else
       AC_MSG_RESULT(SunOS -- sigh)
       dnl for suns without yp or something like that:
@@ -187,7 +192,7 @@ AC_CHECK_SIZEOF(int)
 dnl Checks for header files.
 AC_HEADER_DIRENT
 AC_HEADER_SYS_WAIT
-AC_CHECK_HEADERS(sys/time.h sys/select.h sys/rusage.h unistd.h)
+AC_CHECK_HEADERS(sys/time.h sys/select.h sys/rusage.h unistd.h dlfcn.h)
 
 dnl Checks for typedefs, structures, and compiler characteristics.
 AC_TYPE_PID_T
@@ -196,7 +201,7 @@ AC_HEADER_TIME
 dnl Checks for library functions.
 AC_CHECK_FUNCS(rename getrusage getdtablesize srandom random sigaction)
 AC_CHECK_FUNCS(sigemptyset vsprintf strcasecmp setpgid clock dlopen)
-AC_CHECK_FUNCS(dprintf bzero)
+AC_CHECK_FUNCS(dprintf bzero uname vsnprintf)
 
 if test "${ac_cv_func_vsprintf}" = "no"; then
   echo ""
@@ -206,6 +211,14 @@ if test "${ac_cv_func_vsprintf}" = "no"; then
   exit
 fi
 
+if test "${ac_cv_header_stdc}" = "no"; then
+  echo ""
+  echo "Your system must support ANSI C Header files."
+  echo "These are required for the language support. Sorry."
+  exit
+fi
+
+
 dnl check how much space is left in filedb (informational purposes)
 
 AC_MSG_CHECKING(space left in file database struct)
@@ -214,14 +227,14 @@ cat >abacab.c <<'EOF'
 #include <sys/time.h>
 #include "src/mod/filesys.mod/files.h"
 main() {
-  fprintf(stderr,"%d",512-sizeof(struct filler));
+  fprintf(stderr,"%d/%d",512-sizeof(struct filler),sizeof(filedb));
 }
 EOF
 ${CC} -o abacab abacab.c
 FILEDB_SPACE=`./abacab`
 AC_MSG_RESULT($FILEDB_SPACE bytes)
 rm -f abacab abacab.o abacab.c
-echo "   (standard is currently 28 bytes)"
+echo "   (standard is currently 48/512 bytes)"
 
 dnl where is tcl?  is it here?
 
@@ -407,9 +420,12 @@ else
     TCL_REQS="$TCLLIB/lib$TCLLIBFN"
     TCL_LIBS="-L$TCLLIB -l$TCLLIBFNS -lm"
   else
-    AC_MSG_RESULT(7.3 or earlier -- sigh)
-    TCL_REQS="libtcle.a"
-    TCL_LIBS="-L. -ltcle -lm"
+    echo ""
+    echo "You're tcl version is way to old - Version 7.3 or earlier"
+    echo "I suggest you download and complie a more recent version"
+    echo "The most reliable current version is 7.6"
+    echo ""
+    exit 1
   fi
 fi
 
@@ -420,6 +436,10 @@ AC_SUBST(TCL_REQS)
 AC_SUBST(TCL_LIBS)
 
 # ---------- end of robey's tcl thingies
+
+if test ! "x$GMAKE" = "x"; then
+  SET_MAKE="MAKE=gmake"
+fi
 
 AC_SUBST(EGGEXEC)
 AC_SUBST(CC)
